import request from './request'
const np = (p={}) => ({...p, pageNo:p.pageNo??p.page??1, pageSize:p.pageSize??p.size??10})
export const createWorkOrder = data => request.post('/workorders', data)
export const getWorkOrderById = id => request.get(`/workorders/${id}`)
export const listWorkOrders = () => request.get('/workorders/list')
export const updateWorkOrder = data => request.put('/workorders', data)
export const deleteWorkOrder = id => request.delete(`/workorders/${id}`)
export const assignWorkOrder = (id,data) => request.post(`/workorders/${id}/assign`, data)
export const autoAssignWorkOrder = id => request.post(`/workorders/${id}/auto-assign`)
export const acceptWorkOrder = (id,data={}) => request.post(`/workorders/${id}/accept`, data)
export const addWorkOrderRecord = (id,data) => request.post(`/workorders/${id}/records`, data)
export const finishWorkOrder = (id,data) => request.post(`/workorders/${id}/finish`, data)
export const evaluateWorkOrder = (id,data) => request.post(`/workorders/${id}/evaluate`, data)
export const cancelWorkOrder = (id,data) => request.post(`/workorders/${id}/cancel`, data)
export const pageWorkOrders = (params={}) => request.get('/workorders/page', {params:np(params)})
export const getWorkOrderDetail = id => request.get(`/workorders/${id}/detail`)
